### ISSUE TITLE
溯源的函数不对

### ISSUE THREAD

**Issue by Chi-Kai** [steakliu/blockchain-trace-fabric#2]
使用的复查询函数GetQueryResult() 只是对状态数据库进行查询，而状态数据库是可以进行增删查改的，所以不能作为溯源的依据。应该对区块进行溯源

**Comment by Chi-Kai** [comment]
官方提供的GetHistoryForKey()  可以对区块查询所有的记录，但是他好像是针对 key/value  键值对的查询。对于这种溯源案例，常常有一对多的情况，这个函数也不能用。不知道怎么办

**Comment by steakliu** [comment]
对，这些函数是针对状态数据库counchdb的，而counchdb数据是可以改变的，如果您想直接查询区块链的话，可以通过交易ID去查询区块，这样得到的数据就是不可篡改的了
